language: python
python:
  - "2.7"

sudo: false

addons:
  apt:
    packages:
      - libgsl0-dev
      - libgsl0ldbl
      - libgsl0-dbg
      - swig

install:
  - python setup.py install

script:
  - echo "Build success"
