# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _hod
else:
    import _hod

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class dp(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _hod.dp_swiginit(self, _hod.new_dp())
    __swig_destroy__ = _hod.delete_dp

    def assign(self, value):
        return _hod.dp_assign(self, value)

    def value(self):
        return _hod.dp_value(self)

    def cast(self):
        return _hod.dp_cast(self)

    @staticmethod
    def frompointer(t):
        return _hod.dp_frompointer(t)

# Register dp in _hod:
_hod.dp_swigregister(dp)
class cosmo(object):
    r"""Proxy of C++ cosmo class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Om0 = property(_hod.cosmo_Om0_get, _hod.cosmo_Om0_set, doc=r"""Om0 : double""")
    Omk = property(_hod.cosmo_Omk_get, _hod.cosmo_Omk_set, doc=r"""Omk : double""")
    w0 = property(_hod.cosmo_w0_get, _hod.cosmo_w0_set, doc=r"""w0 : double""")
    wa = property(_hod.cosmo_wa_get, _hod.cosmo_wa_set, doc=r"""wa : double""")
    Omb = property(_hod.cosmo_Omb_get, _hod.cosmo_Omb_set, doc=r"""Omb : double""")
    hval = property(_hod.cosmo_hval_get, _hod.cosmo_hval_set, doc=r"""hval : double""")
    th = property(_hod.cosmo_th_get, _hod.cosmo_th_set, doc=r"""th : double""")
    s8 = property(_hod.cosmo_s8_get, _hod.cosmo_s8_set, doc=r"""s8 : double""")
    nspec = property(_hod.cosmo_nspec_get, _hod.cosmo_nspec_set, doc=r"""nspec : double""")
    ximax = property(_hod.cosmo_ximax_get, _hod.cosmo_ximax_set, doc=r"""ximax : double""")
    cfac = property(_hod.cosmo_cfac_get, _hod.cosmo_cfac_set, doc=r"""cfac : double""")

    def __init__(self):
        r"""__init__(cosmo self) -> cosmo"""
        _hod.cosmo_swiginit(self, _hod.new_cosmo())
    __swig_destroy__ = _hod.delete_cosmo

# Register cosmo in _hod:
_hod.cosmo_swigregister(cosmo)
class gf_par(object):
    r"""Proxy of C++ gf_par class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Omega0 = property(_hod.gf_par_Omega0_get, _hod.gf_par_Omega0_set, doc=r"""Omega0 : double""")
    OmegaL = property(_hod.gf_par_OmegaL_get, _hod.gf_par_OmegaL_set, doc=r"""OmegaL : double""")
    w0 = property(_hod.gf_par_w0_get, _hod.gf_par_w0_set, doc=r"""w0 : double""")
    wa = property(_hod.gf_par_wa_get, _hod.gf_par_wa_set, doc=r"""wa : double""")

    def __init__(self):
        r"""__init__(gf_par self) -> gf_par"""
        _hod.gf_par_swiginit(self, _hod.new_gf_par())
    __swig_destroy__ = _hod.delete_gf_par

# Register gf_par in _hod:
_hod.gf_par_swigregister(gf_par)
class march_params(object):
    r"""Proxy of C++ march_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    fac = property(_hod.march_params_fac_get, _hod.march_params_fac_set, doc=r"""fac : double""")

    def __init__(self):
        r"""__init__(march_params self) -> march_params"""
        _hod.march_params_swiginit(self, _hod.new_march_params())
    __swig_destroy__ = _hod.delete_march_params

# Register march_params in _hod:
_hod.march_params_swigregister(march_params)
class qk_params(object):
    r"""Proxy of C++ qk_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.qk_params_cptr_get, _hod.qk_params_cptr_set, doc=r"""cptr : p.cosmology""")
    k = property(_hod.qk_params_k_get, _hod.qk_params_k_set, doc=r"""k : p.double""")
    z = property(_hod.qk_params_z_get, _hod.qk_params_z_set, doc=r"""z : p.double""")
    xmax = property(_hod.qk_params_xmax_get, _hod.qk_params_xmax_set, doc=r"""xmax : p.double""")
    opt = property(_hod.qk_params_opt_get, _hod.qk_params_opt_set, doc=r"""opt : int""")

    def __init__(self):
        r"""__init__(qk_params self) -> qk_params"""
        _hod.qk_params_swiginit(self, _hod.new_qk_params())
    __swig_destroy__ = _hod.delete_qk_params

# Register qk_params in _hod:
_hod.qk_params_swigregister(qk_params)
class projwpk_params(object):
    r"""Proxy of C++ projwpk_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.projwpk_params_cptr_get, _hod.projwpk_params_cptr_set, doc=r"""cptr : p.cosmology""")
    R = property(_hod.projwpk_params_R_get, _hod.projwpk_params_R_set, doc=r"""R : p.double""")
    z = property(_hod.projwpk_params_z_get, _hod.projwpk_params_z_set, doc=r"""z : p.double""")
    fkai = property(_hod.projwpk_params_fkai_get, _hod.projwpk_params_fkai_set, doc=r"""fkai : p.double""")

    def __init__(self):
        r"""__init__(projwpk_params self) -> projwpk_params"""
        _hod.projwpk_params_swiginit(self, _hod.new_projwpk_params())
    __swig_destroy__ = _hod.delete_projwpk_params

# Register projwpk_params in _hod:
_hod.projwpk_params_swigregister(projwpk_params)
class cDel_params(object):
    r"""Proxy of C++ cDel_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.cDel_params_cptr_get, _hod.cDel_params_cptr_set, doc=r"""cptr : p.cosmology""")
    cvir = property(_hod.cDel_params_cvir_get, _hod.cDel_params_cvir_set, doc=r"""cvir : p.double""")
    omegaz = property(_hod.cDel_params_omegaz_get, _hod.cDel_params_omegaz_set, doc=r"""omegaz : p.double""")
    dcz = property(_hod.cDel_params_dcz_get, _hod.cDel_params_dcz_set, doc=r"""dcz : p.double""")
    Delta = property(_hod.cDel_params_Delta_get, _hod.cDel_params_Delta_set, doc=r"""Delta : p.double""")

    def __init__(self):
        r"""__init__(cDel_params self) -> cDel_params"""
        _hod.cDel_params_swiginit(self, _hod.new_cDel_params())
    __swig_destroy__ = _hod.delete_cDel_params

# Register cDel_params in _hod:
_hod.cDel_params_swigregister(cDel_params)

def dTime(arg1, arg2):
    r"""dTime(double arg1, void * arg2) -> double"""
    return _hod.dTime(arg1, arg2)

def dChi(arg1, arg2):
    r"""dChi(double arg1, void * arg2) -> double"""
    return _hod.dChi(arg1, arg2)

def dneffint(arg1, arg2):
    r"""dneffint(double arg1, void * arg2) -> double"""
    return _hod.dneffint(arg1, arg2)

def dCint(arg1, arg2):
    r"""dCint(double arg1, void * arg2) -> double"""
    return _hod.dCint(arg1, arg2)

def findmvir(arg1, arg2):
    r"""findmvir(double arg1, void * arg2) -> double"""
    return _hod.findmvir(arg1, arg2)

def findksig(arg1, arg2):
    r"""findksig(double arg1, void * arg2) -> double"""
    return _hod.findksig(arg1, arg2)

def dxi_L(arg1, arg2):
    r"""dxi_L(double arg1, void * arg2) -> double"""
    return _hod.dxi_L(arg1, arg2)

def dPktest_L(arg1, arg2):
    r"""dPktest_L(double arg1, void * arg2) -> double"""
    return _hod.dPktest_L(arg1, arg2)

def dPktest_NL(arg1, arg2):
    r"""dPktest_NL(double arg1, void * arg2) -> double"""
    return _hod.dPktest_NL(arg1, arg2)

def dPktest_zetaNL(arg1, arg2):
    r"""dPktest_zetaNL(double arg1, void * arg2) -> double"""
    return _hod.dPktest_zetaNL(arg1, arg2)

def dxi_NL(arg1, arg2):
    r"""dxi_NL(double arg1, void * arg2) -> double"""
    return _hod.dxi_NL(arg1, arg2)

def E_sq(arg1, arg2):
    r"""E_sq(gf_par arg1, double & arg2) -> double"""
    return _hod.E_sq(arg1, arg2)

def dE_sqdz(arg1, arg2):
    r"""dE_sqdz(gf_par arg1, double & arg2) -> double"""
    return _hod.dE_sqdz(arg1, arg2)

def getall(arg1, arg2, arg3, arg4, arg5):
    r"""getall(gf_par arg1, double & arg2, double & arg3, double & arg4, double & arg5)"""
    return _hod.getall(arg1, arg2, arg3, arg4, arg5)

def d2lnE_sqdz2(arg1, arg2):
    r"""d2lnE_sqdz2(gf_par arg1, double & arg2) -> double"""
    return _hod.d2lnE_sqdz2(arg1, arg2)

def gf_func(arg1, arg2, arg3, arg4):
    r"""gf_func(double arg1, double const [] arg2, double [] arg3, void * arg4) -> int"""
    return _hod.gf_func(arg1, arg2, arg3, arg4)

def gf_jac(arg1, arg2, arg3, arg4, arg5):
    r"""gf_jac(double arg1, double const [] arg2, double * arg3, double [] arg4, void * arg5) -> int"""
    return _hod.gf_jac(arg1, arg2, arg3, arg4, arg5)

def findrz(x, params):
    r"""findrz(double x, void * params) -> double"""
    return _hod.findrz(x, params)

def findzmax(x, params):
    r"""findzmax(double x, void * params) -> double"""
    return _hod.findzmax(x, params)

def dwpnl(x, params):
    r"""dwpnl(double x, void * params) -> double"""
    return _hod.dwpnl(x, params)

def dwpl(x, params):
    r"""dwpl(double x, void * params) -> double"""
    return _hod.dwpl(x, params)

def dQk(arg1, arg2):
    r"""dQk(double arg1, void * arg2) -> double"""
    return _hod.dQk(arg1, arg2)

def dxinlbar(arg1, arg2):
    r"""dxinlbar(double arg1, void * arg2) -> double"""
    return _hod.dxinlbar(arg1, arg2)

def dxinlbarbar(arg1, arg2):
    r"""dxinlbarbar(double arg1, void * arg2) -> double"""
    return _hod.dxinlbarbar(arg1, arg2)

def dxilbar(arg1, arg2):
    r"""dxilbar(double arg1, void * arg2) -> double"""
    return _hod.dxilbar(arg1, arg2)

def dxilbarbar(arg1, arg2):
    r"""dxilbarbar(double arg1, void * arg2) -> double"""
    return _hod.dxilbarbar(arg1, arg2)

def dwpnl_kaiser(arg1, arg2):
    r"""dwpnl_kaiser(double arg1, void * arg2) -> double"""
    return _hod.dwpnl_kaiser(arg1, arg2)

def dwpl_kaiser(arg1, arg2):
    r"""dwpl_kaiser(double arg1, void * arg2) -> double"""
    return _hod.dwpl_kaiser(arg1, arg2)

def dvar_G(x, params):
    r"""dvar_G(double x, void * params) -> double"""
    return _hod.dvar_G(x, params)

def dvar_TH(x, params):
    r"""dvar_TH(double x, void * params) -> double"""
    return _hod.dvar_TH(x, params)

def findcmarch(arg1, arg2):
    r"""findcmarch(double arg1, void * arg2) -> double"""
    return _hod.findcmarch(arg1, arg2)

def findcDel(arg1, arg2):
    r"""findcDel(double arg1, void * arg2) -> double"""
    return _hod.findcDel(arg1, arg2)

def findcDelp(arg1, arg2):
    r"""findcDelp(double arg1, void * arg2) -> double"""
    return _hod.findcDelp(arg1, arg2)
class cosmology(object):
    r"""Proxy of C++ cosmology class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _hod.delete_cosmology

    def __init__(self, *args):
        r"""
        __init__(cosmology self) -> cosmology
        __init__(cosmology self, double om0, double omk, double w0, double wa, double omb, double h, double theta, double sigma8, double ns, double ximax, double cfac) -> cosmology
        __init__(cosmology self, cosmo arg2) -> cosmology
        Initializes cosmology object 

        :Parameters:

        -   Omega0 : Matter density parameter
        -   OmegaK : Curvature parameter
        -   w0 : Dark energy equation of state parameter
        -   wa : Dark energy equation of state parameter
        -   Omegab : Baryon density parameter
        -   h : Hubble parameter
        -   ThetaCMB : CMB temperature
        -   sigma8 : sigma8
        -   ns : power spectrum index
        -   psi : Parameter psi defined in van den Bosch 2013, only relevant for halo model calculation
        -   cfac : Constant multiplicative factor for the c-M relation

        :Returns:

        -   Cosmology object

            Without any inputs, initializes to flat WMAP3 LCDM cosmology, cfac=1.0, ximax=log10(8.0).

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> help(a)


        """
        _hod.cosmology_swiginit(self, _hod.new_cosmology(*args))

    def cosmo_free(self):
        r"""
        cosmo_free(cosmology self)
        Frees all memory associated with cosmology object

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.cosmo_free()


        """
        return _hod.cosmology_cosmo_free(self)

    def Dcofz(self, z):
        r"""
        Dcofz(cosmology self, double z) -> double
        Comoving distance as a function of redshift

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Comoving distance

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Dcofz(0.5)


        """
        return _hod.cosmology_Dcofz(self, z)

    def Dlofz(self, z):
        r"""
        Dlofz(cosmology self, double z) -> double
        Luminosity distance as a function of redshift

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Luminosity distance

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Dlofz(0.5)


        """
        return _hod.cosmology_Dlofz(self, z)

    def Daofz(self, z):
        r"""
        Daofz(cosmology self, double z) -> double
        Angular diameter distance as a function of redshift

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Angular diameter distance

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Daofz(0.5)


        """
        return _hod.cosmology_Daofz(self, z)

    def Daofzlh(self, zl, zh):
        r"""
        Daofzlh(cosmology self, double zl, double zh) -> double
        Angular diameter distance as a function of redshift of lens and source

        :Parameters:

        -   zl : Redshift of lens
        -   zh : Redshift of source

        :Returns:

        -   Angular diameter distance between two redshifts

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Daofzlh(0.5,1.0)


        """
        return _hod.cosmology_Daofzlh(self, zl, zh)

    def growthfactor_num(self, z):
        r"""
        growthfactor_num(cosmology self, double z) -> double
        Growth factor as a function of redshift (normalized to unity at redshift zero)

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Growth factor at redshift z

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.growthfactor_num(0.5)


        """
        return _hod.cosmology_growthfactor_num(self, z)

    def dlnDdln1pz(self, z):
        r"""
        dlnDdln1pz(cosmology self, double z) -> double
        Negative of the logarithmic derivative of growth factor with scale factor

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Negative of the logarithmic derivative of growth factor with scale factor

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.dlnDdln1pz(0.5)


        """
        return _hod.cosmology_dlnDdln1pz(self, z)

    def Omega(self, z):
        r"""
        Omega(cosmology self, double z) -> double
        Matter density parameter at redshift z

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Matter density parameter at redshift z

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Omega(0.5)


        """
        return _hod.cosmology_Omega(self, z)

    def Omegaw(self, z):
        r"""
        Omegaw(cosmology self, double z) -> double
        Dark energy density parameter at redshift z

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Dark energy density parameter at redshift z

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Omegaw(0.5)


        """
        return _hod.cosmology_Omegaw(self, z)

    def Delta_crit(self, z):
        r"""
        Delta_crit(cosmology self, double z) -> double
        Virial density contrast at redshift z a'la Bryan and Norman '98

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Virial density contrast (with respect to critical density at redshift z)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Delta_crit(0.5)


        """
        return _hod.cosmology_Delta_crit(self, z)

    def set_optmf(self, opt):
        r"""
        set_optmf(cosmology self, int opt)
        Set mass function option

        :Parameters:

        -   option = 1: Tinker et al. 2010 mass function (well tested and consistent
            with the bias prescription
        -   option = 2: Sheth Tormen mass function
        -   option = 3: Bhattacharya et al. 2010 mass function

        :Returns:

        -   Set mass function choice (default is equal to 1 if this function is not called)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.set_optmf(1)


        """
        return _hod.cosmology_set_optmf(self, opt)

    def Delta2_L_num(self, k, z):
        r"""
        Delta2_L_num(cosmology self, double k, double z) -> double
        Power per logarithmic k interval in the linear matter power spectrum Delta^2(k,z)

        :Parameters:

        -   k: Wavenumber (in h Mpc^{-1})
        -   z: Redshift

        :Returns:

        -   Delta^2(k,z)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Delta2_L_num(0.1,0.0)


        """
        return _hod.cosmology_Delta2_L_num(self, k, z)

    def Delta2_NL_num(self, k, z):
        r"""
        Delta2_NL_num(cosmology self, double k, double z) -> double
        Power per logarithmic k interval in the nonlinear matter power spectrum Delta^2_NL(k,z)

        :Parameters:

        -   k: Wavenumber (in h Mpc^{-1})
        -   z: Redshift

        :Returns:

        -   Nonlinear Delta^2(k,z)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Delta2_NL_num(0.1,0.0)


        """
        return _hod.cosmology_Delta2_NL_num(self, k, z)

    def xi_L_num(self, k, z):
        r"""
        xi_L_num(cosmology self, double k, double z) -> double
        Linear matter correlation function

        :Parameters:

        -   r: Scale (in hinv Mpc)
        -   z: Redshift

        :Returns:

        -   Linear matter correlation function (r,z)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.xi_L_num(0.1,0.0)


        """
        return _hod.cosmology_xi_L_num(self, k, z)

    def xi_NL_num(self, k, z):
        r"""
        xi_NL_num(cosmology self, double k, double z) -> double
        Non-Linear matter correlation function

        :Parameters:

        -   r: Scale (in hinv Mpc)
        -   z: Redshift

        :Returns:

        -   Non-linear matter correlation function (r,z)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.xi_NL_num(0.1,0.0)


        """
        return _hod.cosmology_xi_NL_num(self, k, z)

    def nofm(self, M, z):
        r"""
        nofm(cosmology self, double M, double z) -> double
        Mass function as a function of mass and redshift

        :Parameters:

        -   M: Mass (in hinv Msun)
        -   z: Redshift

        :Returns:

        -   dN(>M)/dM of halos, where N(>M) is the cumulative number density of halos with mass larger than M, commonly referred to as mass function

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.nofm(1e12,0.0)


        """
        return _hod.cosmology_nofm(self, M, z)

    def bias(self, M, z):
        r"""
        bias(cosmology self, double M, double z) -> double
        Halo bias function as a function of mass and redshift

        :Parameters:

        -   M: Mass (in hinv Msun)
        -   z: Redshift

        :Returns:

        -   Large scale halo bias

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.bias(1e12,0.0)


        """
        return _hod.cosmology_bias(self, M, z)

    def varM_TH_num(self, M, z):
        r"""
        varM_TH_num(cosmology self, double M, double z) -> double
        Variance of fluctuations on a given mass scale [sigma^2(M,z)]

        :Parameters:

        -   M: Mass (in hinv Msun)
        -   z: Redshift

        :Returns:

        -   Variance of fluctuations when density field is smoothed on the lagrangian radius corresponding to a given mass scale 

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.varM_TH_num(1e12,0.0)


        """
        return _hod.cosmology_varM_TH_num(self, M, z)

    def varM_TH_num_deriv(self, M, z):
        r"""
        varM_TH_num_deriv(cosmology self, double M, double z) -> double
        dln sigma^2/dln M

        :Parameters:

        -   M: Mass (in hinv Msun)
        -   z: Redshift

        :Returns:

        - dln sigma^2/dln M  (M,z)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.varM_TH_num_deriv(1e12,0.0)


        """
        return _hod.cosmology_varM_TH_num_deriv(self, M, z)

    def Nplus(self, M200, z):
        r"""
        Nplus(cosmology self, double M200, double z) -> double
        Number density of halos with mass above a given mass at a given redshift

        :Parameters:

        -   M: Mass (in hinv Msun)
        -   z: Redshift

        :Returns:

        - N(>M,z)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Nplus(1e12,0.0)


        """
        return _hod.cosmology_Nplus(self, M200, z)

    def getM(self, Nplus, z):
        r"""
        getM(cosmology self, double Nplus, double z) -> double
        Find mass such that halos with mass larger than it have a given number density at a given redshift

        :Parameters:

        -   Nplus: Target number density (in h^3 Mpc^{-3})
        -   z: Redshift

        :Returns:

        -   M: Mass (hinv Msun)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.getM(1e-6,0.0)


        """
        return _hod.cosmology_getM(self, Nplus, z)

    def modelNFWhalo(self, M200, z):
        r"""
        modelNFWhalo(cosmology self, double M200, double z)
        Output the virial mass, physical virial radius, virial
        concentration of a halo, its physical radius with density
        contrast 200m and the corresponding concentration c200m
        given a mass M200m at redshift z

        :Parameters:

        -   M200m: Mass (hinv Msun) defined 200 times overdense with respect to the background
        -   z: Redshift

        :Returns:

        -   Mvir : The virial mass (hinv Msun)
        -   Rvir : The physical virial radius (hinv Mpc)
        -   cvir : The virial concentration
        -   R200m : The physical boundary of halo 200 times overdense with respect to background density (hinv Mpc)
        -   c200m : The concentration of halo 200 times overdense with respect to background density

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.modelNFWhalo(1e12,0.0)


        """
        return _hod.cosmology_modelNFWhalo(self, M200, z)

    def modelNFWhalo_com(self, M200, z):
        r"""
        modelNFWhalo_com(cosmology self, double M200, double z)
        Output the virial mass, comoving virial radius, virial
        concentration of a halo, its comoving radius with density
        contrast 200m and the corresponding concentration c200m
        given a mass M200m at redshift z

        :Parameters:

        -   M200m: Mass (hinv Msun) defined 200 times overdense with respect to the background
        -   z: Redshift

        :Returns:

        -   Mvir : The virial mass (hinv Msun)
        -   Rvir : The comoving virial radius (hinv Mpc)
        -   cvir : The virial concentration
        -   R200m : The comoving boundary of halo 200 times overdense with respect to background density (hinv Mpc)
        -   c200m : The concentration of halo 200 times overdense with respect to background density

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.modelNFWhalo_com(1e12,0.0)


        """
        return _hod.cosmology_modelNFWhalo_com(self, M200, z)

    def conc(self, Mvir, z):
        r"""
        conc(cosmology self, double Mvir, double z) -> double
        Concentration of halos

        :Parameters:

        -   Mvir: Virial mass (hinv Msun) 
        -   z: Redshift

        :Returns:

        -   cvir : The virial concentration

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.conc(1e12,0.0)


        """
        return _hod.cosmology_conc(self, Mvir, z)

    def Eofz(self, z):
        r"""
        Eofz(cosmology self, double z) -> double
        Returns the cosmological expansion function E(z)

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Eofz: Expansion function

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Eofz(0.5)
            1.28111279753

        """
        return _hod.cosmology_Eofz(self, z)

    def setnew_z(self, z):
        r"""
        setnew_z(cosmology self, double z)
        Reset the global redshift at which many of the splines in the cosmology code are initialized. This is rarely used function.

        :Parameters:

        -   z : Redshift

        :Returns:

        -   None: None

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.setnew_z(0.5)
            1

        """
        return _hod.cosmology_setnew_z(self, z)

    def gets8(self):
        r"""
        gets8(cosmology self) -> double
        Output value of sigma8

        :Parameters:

        -   None : No inputs

        :Returns:

        -   sigma8 : sigma8

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.gets8()

        """
        return _hod.cosmology_gets8(self)

    def getOmb(self):
        r"""
        getOmb(cosmology self) -> double
        Output value of Omegab

        :Parameters:

        -   None : No input parameters

        :Returns:

        -   Omegab : Baryon density parameter

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.getOmb()

        """
        return _hod.cosmology_getOmb(self)

    def geth(self):
        r"""
        geth(cosmology self) -> double
        Output value of h value

        :Parameters:

        -   None : No input parameters

        :Returns:

        -   h : Hubble parameter

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.geth()

        """
        return _hod.cosmology_geth(self)

    def getns(self):
        r"""
        getns(cosmology self) -> double
        Output value of spectral index

        :Parameters:

        -   None : No input parameters

        :Returns:

        -   ns : Spectral index of initial density fluctuations

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.getns()

        """
        return _hod.cosmology_getns(self)

    def getxinlzetamax(self):
        r"""
        getxinlzetamax(cosmology self) -> double
        Returns the value of psi from van den Bosch 2013

        :Parameters:

        -   None : No input parameters

        :Returns:

        -   psi : Psi defined in van den Bosch 2013

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.getxinlzetamax()

        """
        return _hod.cosmology_getxinlzetamax(self)

    def get_cfac(self):
        r"""
        get_cfac(cosmology self) -> double
        Returns factor multiplying all concentrations calculated by the code

        :Parameters:

        -   None : No input parameters

        :Returns:

        -   cfac : Factor multiplying all concentrations output by the code

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.get_cfac()

        """
        return _hod.cosmology_get_cfac(self)

    def set_cfac(self, cfac):
        r"""
        set_cfac(cosmology self, double cfac) -> double
        Sets factor multiplying all concentrations calculated by the code

        :Parameters:

        -   cfac : Factor multiplying all concentrations output by the code

        :Returns:

        -   None : None

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.set_cfac(1.0)

        """
        return _hod.cosmology_set_cfac(self, cfac)

    def getzmax(self, xL):
        r"""
        getzmax(cosmology self, double xL) -> double
        Get the maximum redshift to which a galaxy can be observed by SDSS spectroscopic survey

        :Parameters:

        -   xL: Luminosity in h^{-2} Lsun

        :Returns:

        -   z : Redshift

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.getzmax(1e12)

        """
        return _hod.cosmology_getzmax(self, xL)

    def getLmin(self, z, L1):
        r"""
        getLmin(cosmology self, double z, double L1) -> double
        Get the minimum luminosity of galaxies that can be observed by SDSS spectroscopic survey at a given redshift

        :Parameters:

        -   z : Redshift

        :Returns:

        -   xL: Luminosity in h^{-2} Lsun

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.getLmin(0.1)

        """
        return _hod.cosmology_getLmin(self, z, L1)

    def Time(self, z):
        r"""
        Time(cosmology self, double z) -> double
        Get the time in units of 1/(H_0 km/s/Mpc/yr)

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Time : in units of 1/(H_0 km/s/Mpc/yr)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Time(0.1)

        """
        return _hod.cosmology_Time(self, z)

    def Lookback(self, z):
        r"""
        Lookback(cosmology self, double z) -> double
        Get the lookback time in units of 1/(H_0 km/s/Mpc/yr)

        :Parameters:

        -   z : Redshift

        :Returns:

        -   Lookback Time : in units of 1/(H_0 km/s/Mpc/yr)

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.Lookback(0.1)

        """
        return _hod.cosmology_Lookback(self, z)

    def wpnl(self, z, rad, projmax):
        r"""
        wpnl(cosmology self, double z, double rad, double projmax) -> double
        Get the projected non-linear matter correlation function

        :Parameters:

        -   r : Separation of galaxies
        -   z : Redshift
        -   pimax : Line-of-sight integration limit

        :Returns:

        -   wpnl : Projected non-linear matter correlation function

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.wpnl(0.1,0.1,100.0)

        """
        return _hod.cosmology_wpnl(self, z, rad, projmax)

    def wpl(self, z, rad, projmax):
        r"""
        wpl(cosmology self, double z, double rad, double projmax) -> double
        Get the projected linear matter correlation function

        :Parameters:

        -   r : Separation of galaxies
        -   z : Redshift
        -   pimax : Line-of-sight integration limit

        :Returns:

        -   wpl : Projected linear matter correlation function

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.wpl(0.1,0.1,100.0)

        """
        return _hod.cosmology_wpl(self, z, rad, projmax)

    def wpnl_kaiser(self, z, rad, projmax, fkai):
        r"""
        wpnl_kaiser(cosmology self, double z, double rad, double projmax, double fkai) -> double
        Get the projected non-linear matter correlation function accounting for Kaiser effects

        :Parameters:

        -   r : Separation of galaxies
        -   z : Redshift
        -   pimax : Line-of-sight integration limit
        -   fkai : Kaiser factor f/b

        :Returns:

        -   wpnl_kaiser : Projected non-linear matter correlation function

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.wpnl_kaiser(0.1,0.1,100.0,1.0)

        """
        return _hod.cosmology_wpnl_kaiser(self, z, rad, projmax, fkai)

    def xi_NL_kaiser(self, r, z, mu, fkai):
        r"""
        xi_NL_kaiser(cosmology self, double r, double z, double mu, double fkai) -> double
        Get the non-linear matter correlation function accounting for Kaiser effects

        :Parameters:

        -   r : Separation of galaxies
        -   z : Redshift
        -   mu : Cosine of angle between separation vector and line of sight
        -   fkai : Kaiser factor f/b

        :Returns:

        -   xi_nl_kaiser : Non-linear matter correlation function

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.xi_nl_kaiser(0.1,0.1,0.5,1.0)

        """
        return _hod.cosmology_xi_NL_kaiser(self, r, z, mu, fkai)

    def wpl_kaiser(self, z, rad, projmax, fkai):
        r"""
        wpl_kaiser(cosmology self, double z, double rad, double projmax, double fkai) -> double
        Get the projected linear matter correlation function accounting for Kaiser effect

        :Parameters:

        -   r : Separation of galaxies
        -   z : Redshift
        -   pimax : Line-of-sight integration limit
        -   fkai : Kaiser factor f/b

        :Returns:

        -   wpl : Projected linear matter correlation function

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.wpl_kaiser(0.1,0.1,100.0,1.0)

        """
        return _hod.cosmology_wpl_kaiser(self, z, rad, projmax, fkai)

    def xi_L_kaiser(self, r, z, mu, fkai):
        r"""
        xi_L_kaiser(cosmology self, double r, double z, double mu, double fkai) -> double
        Get the linear matter correlation function accounting for Kaiser effect

        :Parameters:

        -   r : Separation of galaxies
        -   z : Redshift
        -   mu : Cosine of angle between separation vector and line of sight
        -   fkai : Kaiser factor f/b

        :Returns:

        -   xi_l : Linear matter correlation function

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.xi_L_kaiser(0.1,0.1,0.5,1.0)

        """
        return _hod.cosmology_xi_L_kaiser(self, r, z, mu, fkai)

    def renew(self, p):
        r"""renew(cosmology self, cosmo p)"""
        return _hod.cosmology_renew(self, p)

    def rsound(self):
        r"""
        rsound(cosmology self) -> double
        Get the comoving sound horizon at the drag epoch

        :Parameters:

        -   None : None

        :Returns:

        -   rsound : Comoving sound horizon at drag epoch a'la Eisenstein and Hu 98

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.rsound()

        """
        return _hod.cosmology_rsound(self)

    def get_deltapi(self, z1, z2):
        r"""
        get_deltapi(cosmology self, double z1, double z2) -> double
        Calculate the line of sight separation between two galaxies

        :Parameters:

        -   z1 : Redshift
        -   z2 : Redshift

        :Returns:

        -   Line of sight separation between two galaxies

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.get_deltapi(0.0, 0.2)


        """
        return _hod.cosmology_get_deltapi(self, z1, z2)

    def get_sinsqang(self, x1, y1, z1, x2, y2, z2):
        r"""
        get_sinsqang(cosmology self, double x1, double y1, double z1, double x2, double y2, double z2) -> double
        Calculate the square of the sin of the angle between two galaxies

        :Parameters:

        -   x1 : Cartesian x for the unit vector pointing at Galaxy 1
        -   y1 : Cartesian y for the unit vector pointing at Galaxy 1
        -   z1 : Cartesian z for the unit vector pointing at Galaxy 1
        -   x2 : Cartesian x for the unit vector pointing at Galaxy 2
        -   y2 : Cartesian y for the unit vector pointing at Galaxy 2
        -   z2 : Cartesian z for the unit vector pointing at Galaxy 2

        :Returns:

        -   Square of the sin of the angle between two galaxies

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.get_sinsqang(0.0, 1.0, 0.0, 1.0, 0.0, 0.0)


        """
        return _hod.cosmology_get_sinsqang(self, x1, y1, z1, x2, y2, z2)

    def get_logrp(self, x1, y1, z1, x2, y2, z2, Chisq):
        r"""
        get_logrp(cosmology self, double x1, double y1, double z1, double x2, double y2, double z2, double Chisq) -> double
        Calculate the projected separation between two galaxies

        :Parameters:

        -   x1 : Cartesian x for the unit vector pointing at Galaxy 1
        -   y1 : Cartesian y for the unit vector pointing at Galaxy 1
        -   z1 : Cartesian z for the unit vector pointing at Galaxy 1
        -   x2 : Cartesian x for the unit vector pointing at Galaxy 2
        -   y2 : Cartesian y for the unit vector pointing at Galaxy 2
        -   z2 : Cartesian z for the unit vector pointing at Galaxy 2

        :Returns:

        -   Log of projected separation between two galaxies

        :Examples:

        >>> import cosmology as cc
        >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
        >>> a.get_logrp(0.0, 1.0, 0.0, 1.0, 0.0, 0.0)


        """
        return _hod.cosmology_get_logrp(self, x1, y1, z1, x2, y2, z2, Chisq)

    def getmstar(self):
        r"""getmstar(cosmology self) -> double"""
        return _hod.cosmology_getmstar(self)

    def pevolve_fixed(self, cdel, opt, z, zstart):
        r"""
        pevolve_fixed(cosmology self, double cdel, int opt, double z, double zstart)
        Pseudo-evolution estimate for the mass (backward or forward):
        Assume that the physical density profile of a peak with
        concentration cdel at redshift zstart defined to be of type
        opt 
        remains fixed. Calculate its concentration at redshift z, and
        the ratio of its mass to the mass at redshift zstart.

        :Parameters:

        -   cdel : concentration of halo 
        -   opt : opt=1: Defined with respect to background density, opt=2: Defined to be virial mass, opt=3: Defined with respect to critical density
        -   z: Redshift
        -   zstart : The reference redshift at which the halo density profile is fixed

        :Returns:

        -   cdelz : The concentration of the halo at redshift z
        -   fdelz : The ratio of the mass at redshift z to the mass at redshift zstart

        :Examples:

            >>> import cosmology as cc
            >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
            >>> a.pevolve_fixed(12.0,1,1.0,0.0)
            [5.019071157921484, 0.585350923353302]

        """
        return _hod.cosmology_pevolve_fixed(self, cdel, opt, z, zstart)

    def getcDel(self, cvir, z, Delta):
        r"""
        getcDel(cosmology self, double cvir, double z, double Delta) -> double
        Output the concentration, cDelta, of a halo defined as Delta
        with respect to the background density at redshift z and which
        has virial concentration equal to cvir.

        :Parameters:

        -   cvir : The virial concentration
        -   z : Redshift
        -   Del : The overdensity with respect to the background

        :Returns:

        -   cDelta : The concentration of this halo when defined as Del times overdense with respect to the background

        :Examples:

            >>> import cosmology as cc
            >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
            >>> a.getcDel(10.0,0.0,200.)
            12.6784160959

        """
        return _hod.cosmology_getcDel(self, cvir, z, Delta)

    def getRvirfromMvir(self, Mvir, z):
        r"""
        getRvirfromMvir(cosmology self, double Mvir, double z) -> double
        Compute the comoving virial radius from the virial mass

        :Parameters:

        -   Mvir : Virial mass
        -   z: Redshift

        :Returns:

        -   Rvir : The comoving virial radius

        :Examples:

            >>> import cosmology as cc
            >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
            >>> a.getRvirfromMvir(1.E12, 0.0)

        """
        return _hod.cosmology_getRvirfromMvir(self, Mvir, z)

    def getRDelfromMDel(self, Mdel, z, Del):
        r"""
        getRDelfromMDel(cosmology self, double Mdel, double z, double Del) -> double
        Compute the comoving halo radius from the halo mass with overdensity Delta

        :Parameters:

        -   MDel : Halo mass
        -   z: Redshift
        -   Del: Overdensity

        :Returns:

        -   RDel : The comoving halo boundary

        :Examples:

            >>> import cosmology as cc
            >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
            >>> a.getRDelfromMDel(1.E12, 0.0, 200.0)

        """
        return _hod.cosmology_getRDelfromMDel(self, Mdel, z, Del)

    def getcDeltap_from_cDelta(self, cDelta, Delta, Deltap):
        r"""
        getcDeltap_from_cDelta(cosmology self, double cDelta, double Delta, double Deltap) -> double
        Output the concentration, cDeltap, of a NFW halo defined as Deltap with respect
        to the background density and which has concentration with respect to another
        definition, Delta, equal to cDelta.

        :Parameters:

        -   cDelta : The virial concentration
        -   Delta : The overdensity with respect to the background
        -   Deltap : The new overdensity with respect to the background at which to
            output concentration

        :Returns:

        -   cDeltap : The concentration of this halo when defined as Deltap times overdense with respect to the background

        :Examples:

            >>> import cosmology as cc
            >>> a = cc.cosmology(0.27,0.0,-1.0,0.0,0.0476,0.7,2.726,0.8,0.96,log10(8.0),1.0)
            >>> a.getcDeltap_from_cDelta(30.0, 200.0, 360.0)

        """
        return _hod.cosmology_getcDeltap_from_cDelta(self, cDelta, Delta, Deltap)

    def bias_TI10_wDelta(self, M, z, Delta):
        r"""bias_TI10_wDelta(cosmology self, double M, double z, double Delta) -> double"""
        return _hod.cosmology_bias_TI10_wDelta(self, M, z, Delta)

    def MF_TI09_500c(self, M, z):
        r"""MF_TI09_500c(cosmology self, double M, double z) -> double"""
        return _hod.cosmology_MF_TI09_500c(self, M, z)

# Register cosmology in _hod:
_hod.cosmology_swigregister(cosmology)
class np_params(object):
    r"""Proxy of C++ np_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.np_params_cptr_get, _hod.np_params_cptr_set, doc=r"""cptr : p.cosmology""")
    z = property(_hod.np_params_z_get, _hod.np_params_z_set, doc=r"""z : p.double""")
    Np = property(_hod.np_params_Np_get, _hod.np_params_Np_set, doc=r"""Np : p.double""")

    def __init__(self):
        r"""__init__(np_params self) -> np_params"""
        _hod.np_params_swiginit(self, _hod.new_np_params())
    __swig_destroy__ = _hod.delete_np_params

# Register np_params in _hod:
_hod.np_params_swigregister(np_params)
class c_params(object):
    r"""Proxy of C++ c_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.c_params_cptr_get, _hod.c_params_cptr_set, doc=r"""cptr : p.cosmology""")

    def __init__(self):
        r"""__init__(c_params self) -> c_params"""
        _hod.c_params_swiginit(self, _hod.new_c_params())
    __swig_destroy__ = _hod.delete_c_params

# Register c_params in _hod:
_hod.c_params_swigregister(c_params)
class coll_params(object):
    r"""Proxy of C++ coll_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.coll_params_cptr_get, _hod.coll_params_cptr_set, doc=r"""cptr : p.cosmology""")
    sig = property(_hod.coll_params_sig_get, _hod.coll_params_sig_set, doc=r"""sig : p.double""")

    def __init__(self):
        r"""__init__(coll_params self) -> coll_params"""
        _hod.coll_params_swiginit(self, _hod.new_coll_params())
    __swig_destroy__ = _hod.delete_coll_params

# Register coll_params in _hod:
_hod.coll_params_swigregister(coll_params)
class mvir_params(object):
    r"""Proxy of C++ mvir_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.mvir_params_cptr_get, _hod.mvir_params_cptr_set, doc=r"""cptr : p.cosmology""")
    m200 = property(_hod.mvir_params_m200_get, _hod.mvir_params_m200_set, doc=r"""m200 : p.double""")
    z = property(_hod.mvir_params_z_get, _hod.mvir_params_z_set, doc=r"""z : p.double""")

    def __init__(self):
        r"""__init__(mvir_params self) -> mvir_params"""
        _hod.mvir_params_swiginit(self, _hod.new_mvir_params())
    __swig_destroy__ = _hod.delete_mvir_params

# Register mvir_params in _hod:
_hod.mvir_params_swigregister(mvir_params)
class c200_params(object):
    r"""Proxy of C++ c200_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.c200_params_cptr_get, _hod.c200_params_cptr_set, doc=r"""cptr : p.cosmology""")
    cvir = property(_hod.c200_params_cvir_get, _hod.c200_params_cvir_set, doc=r"""cvir : p.double""")
    omegaz = property(_hod.c200_params_omegaz_get, _hod.c200_params_omegaz_set, doc=r"""omegaz : p.double""")
    dcz = property(_hod.c200_params_dcz_get, _hod.c200_params_dcz_set, doc=r"""dcz : p.double""")

    def __init__(self):
        r"""__init__(c200_params self) -> c200_params"""
        _hod.c200_params_swiginit(self, _hod.new_c200_params())
    __swig_destroy__ = _hod.delete_c200_params

# Register c200_params in _hod:
_hod.c200_params_swigregister(c200_params)
class cDelta_params(object):
    r"""Proxy of C++ cDelta_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cDelta = property(_hod.cDelta_params_cDelta_get, _hod.cDelta_params_cDelta_set, doc=r"""cDelta : p.double""")
    frac = property(_hod.cDelta_params_frac_get, _hod.cDelta_params_frac_set, doc=r"""frac : p.double""")

    def __init__(self):
        r"""__init__(cDelta_params self) -> cDelta_params"""
        _hod.cDelta_params_swiginit(self, _hod.new_cDelta_params())
    __swig_destroy__ = _hod.delete_cDelta_params

# Register cDelta_params in _hod:
_hod.cDelta_params_swigregister(cDelta_params)
class cvar_params(object):
    r"""Proxy of C++ cvar_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.cvar_params_cptr_get, _hod.cvar_params_cptr_set, doc=r"""cptr : p.cosmology""")
    R = property(_hod.cvar_params_R_get, _hod.cvar_params_R_set, doc=r"""R : p.double""")
    z = property(_hod.cvar_params_z_get, _hod.cvar_params_z_set, doc=r"""z : p.double""")
    psinit = property(_hod.cvar_params_psinit_get, _hod.cvar_params_psinit_set, doc=r"""psinit : p.bool""")

    def __init__(self):
        r"""__init__(cvar_params self) -> cvar_params"""
        _hod.cvar_params_swiginit(self, _hod.new_cvar_params())
    __swig_destroy__ = _hod.delete_cvar_params

# Register cvar_params in _hod:
_hod.cvar_params_swigregister(cvar_params)
class pk_params(object):
    r"""Proxy of C++ pk_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.pk_params_cptr_get, _hod.pk_params_cptr_set, doc=r"""cptr : p.cosmology""")
    k = property(_hod.pk_params_k_get, _hod.pk_params_k_set, doc=r"""k : p.double""")
    z = property(_hod.pk_params_z_get, _hod.pk_params_z_set, doc=r"""z : p.double""")

    def __init__(self):
        r"""__init__(pk_params self) -> pk_params"""
        _hod.pk_params_swiginit(self, _hod.new_pk_params())
    __swig_destroy__ = _hod.delete_pk_params

# Register pk_params in _hod:
_hod.pk_params_swigregister(pk_params)
class xi_params(object):
    r"""Proxy of C++ xi_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.xi_params_cptr_get, _hod.xi_params_cptr_set, doc=r"""cptr : p.cosmology""")
    r = property(_hod.xi_params_r_get, _hod.xi_params_r_set, doc=r"""r : p.double""")
    z = property(_hod.xi_params_z_get, _hod.xi_params_z_set, doc=r"""z : p.double""")

    def __init__(self):
        r"""__init__(xi_params self) -> xi_params"""
        _hod.xi_params_swiginit(self, _hod.new_xi_params())
    __swig_destroy__ = _hod.delete_xi_params

# Register xi_params in _hod:
_hod.xi_params_swigregister(xi_params)
class ksig_params(object):
    r"""Proxy of C++ ksig_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.ksig_params_cptr_get, _hod.ksig_params_cptr_set, doc=r"""cptr : p.cosmology""")
    z = property(_hod.ksig_params_z_get, _hod.ksig_params_z_set, doc=r"""z : p.double""")

    def __init__(self):
        r"""__init__(ksig_params self) -> ksig_params"""
        _hod.ksig_params_swiginit(self, _hod.new_ksig_params())
    __swig_destroy__ = _hod.delete_ksig_params

# Register ksig_params in _hod:
_hod.ksig_params_swigregister(ksig_params)
class projwp_params(object):
    r"""Proxy of C++ projwp_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.projwp_params_cptr_get, _hod.projwp_params_cptr_set, doc=r"""cptr : p.cosmology""")
    R = property(_hod.projwp_params_R_get, _hod.projwp_params_R_set, doc=r"""R : p.double""")
    z = property(_hod.projwp_params_z_get, _hod.projwp_params_z_set, doc=r"""z : p.double""")

    def __init__(self):
        r"""__init__(projwp_params self) -> projwp_params"""
        _hod.projwp_params_swiginit(self, _hod.new_projwp_params())
    __swig_destroy__ = _hod.delete_projwp_params

# Register projwp_params in _hod:
_hod.projwp_params_swigregister(projwp_params)
class rz_params(object):
    r"""Proxy of C++ rz_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.rz_params_cptr_get, _hod.rz_params_cptr_set, doc=r"""cptr : p.cosmology""")
    z = property(_hod.rz_params_z_get, _hod.rz_params_z_set, doc=r"""z : p.double""")
    tgt = property(_hod.rz_params_tgt_get, _hod.rz_params_tgt_set, doc=r"""tgt : p.double""")

    def __init__(self):
        r"""__init__(rz_params self) -> rz_params"""
        _hod.rz_params_swiginit(self, _hod.new_rz_params())
    __swig_destroy__ = _hod.delete_rz_params

# Register rz_params in _hod:
_hod.rz_params_swigregister(rz_params)
class z_params(object):
    r"""Proxy of C++ z_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cptr = property(_hod.z_params_cptr_get, _hod.z_params_cptr_set, doc=r"""cptr : p.cosmology""")
    mag = property(_hod.z_params_mag_get, _hod.z_params_mag_set, doc=r"""mag : p.double""")

    def __init__(self):
        r"""__init__(z_params self) -> z_params"""
        _hod.z_params_swiginit(self, _hod.new_z_params())
    __swig_destroy__ = _hod.delete_z_params

# Register z_params in _hod:
_hod.z_params_swigregister(z_params)

def new_dArray(nelements):
    r"""new_dArray(size_t nelements) -> double *"""
    return _hod.new_dArray(nelements)

def delete_dArray(ary):
    r"""delete_dArray(double * ary)"""
    return _hod.delete_dArray(ary)

def dArray_getitem(ary, index):
    r"""dArray_getitem(double * ary, size_t index) -> double"""
    return _hod.dArray_getitem(ary, index)

def dArray_setitem(ary, index, value):
    r"""dArray_setitem(double * ary, size_t index, double value)"""
    return _hod.dArray_setitem(ary, index, value)
class doubleArray(object):
    r"""Proxy of C++ doubleArray class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        r"""__init__(doubleArray self, size_t nelements) -> doubleArray"""
        _hod.doubleArray_swiginit(self, _hod.new_doubleArray(nelements))
    __swig_destroy__ = _hod.delete_doubleArray

    def __getitem__(self, index):
        r"""__getitem__(doubleArray self, size_t index) -> double"""
        return _hod.doubleArray___getitem__(self, index)

    def __setitem__(self, index, value):
        r"""__setitem__(doubleArray self, size_t index, double value)"""
        return _hod.doubleArray___setitem__(self, index, value)

    def cast(self):
        r"""cast(doubleArray self) -> double *"""
        return _hod.doubleArray_cast(self)

    @staticmethod
    def frompointer(t):
        r"""frompointer(double * t) -> doubleArray"""
        return _hod.doubleArray_frompointer(t)

# Register doubleArray in _hod:
_hod.doubleArray_swigregister(doubleArray)
TINK = _hod.TINK

OFFNEW = _hod.OFFNEW

class auxncen_params(object):
    r"""Proxy of C++ auxncen_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    hptr = property(_hod.auxncen_params_hptr_get, _hod.auxncen_params_hptr_set, doc=r"""hptr : p.hod""")
    xm = property(_hod.auxncen_params_xm_get, _hod.auxncen_params_xm_set, doc=r"""xm : double""")

    def __init__(self):
        r"""__init__(auxncen_params self) -> auxncen_params"""
        _hod.auxncen_params_swiginit(self, _hod.new_auxncen_params())
    __swig_destroy__ = _hod.delete_auxncen_params

# Register auxncen_params in _hod:
_hod.auxncen_params_swigregister(auxncen_params)
class phi_params(object):
    r"""Proxy of C++ phi_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    hptr = property(_hod.phi_params_hptr_get, _hod.phi_params_hptr_set, doc=r"""hptr : p.hod""")
    z = property(_hod.phi_params_z_get, _hod.phi_params_z_set, doc=r"""z : double""")

    def __init__(self):
        r"""__init__(phi_params self) -> phi_params"""
        _hod.phi_params_swiginit(self, _hod.new_phi_params())
    __swig_destroy__ = _hod.delete_phi_params

# Register phi_params in _hod:
_hod.phi_params_swigregister(phi_params)
class proj_params(object):
    r"""Proxy of C++ proj_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    hptr = property(_hod.proj_params_hptr_get, _hod.proj_params_hptr_set, doc=r"""hptr : p.hod""")
    R = property(_hod.proj_params_R_get, _hod.proj_params_R_set, doc=r"""R : p.double""")
    z = property(_hod.proj_params_z_get, _hod.proj_params_z_set, doc=r"""z : p.double""")

    def __init__(self):
        r"""__init__(proj_params self) -> proj_params"""
        _hod.proj_params_swiginit(self, _hod.new_proj_params())
    __swig_destroy__ = _hod.delete_proj_params

# Register proj_params in _hod:
_hod.proj_params_swigregister(proj_params)
class xi_gd_params(object):
    r"""Proxy of C++ xi_gd_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    hptr = property(_hod.xi_gd_params_hptr_get, _hod.xi_gd_params_hptr_set, doc=r"""hptr : p.hod""")
    r = property(_hod.xi_gd_params_r_get, _hod.xi_gd_params_r_set, doc=r"""r : p.double""")
    z = property(_hod.xi_gd_params_z_get, _hod.xi_gd_params_z_set, doc=r"""z : p.double""")

    def __init__(self):
        r"""__init__(xi_gd_params self) -> xi_gd_params"""
        _hod.xi_gd_params_swiginit(self, _hod.new_xi_gd_params())
    __swig_destroy__ = _hod.delete_xi_gd_params

# Register xi_gd_params in _hod:
_hod.xi_gd_params_swigregister(xi_gd_params)
class xi_gg_params(object):
    r"""Proxy of C++ xi_gg_params class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    hptr = property(_hod.xi_gg_params_hptr_get, _hod.xi_gg_params_hptr_set, doc=r"""hptr : p.hod""")
    r = property(_hod.xi_gg_params_r_get, _hod.xi_gg_params_r_set, doc=r"""r : p.double""")
    z = property(_hod.xi_gg_params_z_get, _hod.xi_gg_params_z_set, doc=r"""z : p.double""")

    def __init__(self):
        r"""__init__(xi_gg_params self) -> xi_gg_params"""
        _hod.xi_gg_params_swiginit(self, _hod.new_xi_gg_params())
    __swig_destroy__ = _hod.delete_xi_gg_params

# Register xi_gg_params in _hod:
_hod.xi_gg_params_swigregister(xi_gg_params)
class hodpars(object):
    r"""Proxy of C++ hodpars class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Mmin = property(_hod.hodpars_Mmin_get, _hod.hodpars_Mmin_set, doc=r"""Mmin : double""")
    siglogM = property(_hod.hodpars_siglogM_get, _hod.hodpars_siglogM_set, doc=r"""siglogM : double""")
    Msat = property(_hod.hodpars_Msat_get, _hod.hodpars_Msat_set, doc=r"""Msat : double""")
    alpsat = property(_hod.hodpars_alpsat_get, _hod.hodpars_alpsat_set, doc=r"""alpsat : double""")
    Mcut = property(_hod.hodpars_Mcut_get, _hod.hodpars_Mcut_set, doc=r"""Mcut : double""")
    logM0 = property(_hod.hodpars_logM0_get, _hod.hodpars_logM0_set, doc=r"""logM0 : double""")
    logM1 = property(_hod.hodpars_logM1_get, _hod.hodpars_logM1_set, doc=r"""logM1 : double""")
    alpha = property(_hod.hodpars_alpha_get, _hod.hodpars_alpha_set, doc=r"""alpha : double""")
    beta = property(_hod.hodpars_beta_get, _hod.hodpars_beta_set, doc=r"""beta : double""")
    sig0 = property(_hod.hodpars_sig0_get, _hod.hodpars_sig0_set, doc=r"""sig0 : double""")
    b0 = property(_hod.hodpars_b0_get, _hod.hodpars_b0_set, doc=r"""b0 : double""")
    b1 = property(_hod.hodpars_b1_get, _hod.hodpars_b1_set, doc=r"""b1 : double""")
    b2 = property(_hod.hodpars_b2_get, _hod.hodpars_b2_set, doc=r"""b2 : double""")
    eta = property(_hod.hodpars_eta_get, _hod.hodpars_eta_set, doc=r"""eta : double""")
    alpha_15 = property(_hod.hodpars_alpha_15_get, _hod.hodpars_alpha_15_set, doc=r"""alpha_15 : double""")
    logMa = property(_hod.hodpars_logMa_get, _hod.hodpars_logMa_set, doc=r"""logMa : double""")
    logMb = property(_hod.hodpars_logMb_get, _hod.hodpars_logMb_set, doc=r"""logMb : double""")
    logR0 = property(_hod.hodpars_logR0_get, _hod.hodpars_logR0_set, doc=r"""logR0 : double""")
    logM1_R = property(_hod.hodpars_logM1_R_get, _hod.hodpars_logM1_R_set, doc=r"""logM1_R : double""")
    alphaR = property(_hod.hodpars_alphaR_get, _hod.hodpars_alphaR_set, doc=r"""alphaR : double""")
    betaR = property(_hod.hodpars_betaR_get, _hod.hodpars_betaR_set, doc=r"""betaR : double""")
    sigR = property(_hod.hodpars_sigR_get, _hod.hodpars_sigR_set, doc=r"""sigR : double""")
    logRa = property(_hod.hodpars_logRa_get, _hod.hodpars_logRa_set, doc=r"""logRa : double""")
    logRb = property(_hod.hodpars_logRb_get, _hod.hodpars_logRb_set, doc=r"""logRb : double""")
    corr_coeff = property(_hod.hodpars_corr_coeff_get, _hod.hodpars_corr_coeff_set, doc=r"""corr_coeff : double""")
    fac = property(_hod.hodpars_fac_get, _hod.hodpars_fac_set, doc=r"""fac : double""")
    csbycdm = property(_hod.hodpars_csbycdm_get, _hod.hodpars_csbycdm_set, doc=r"""csbycdm : double""")

    def __init__(self):
        r"""__init__(hodpars self) -> hodpars"""
        _hod.hodpars_swiginit(self, _hod.new_hodpars())
    __swig_destroy__ = _hod.delete_hodpars

# Register hodpars in _hod:
_hod.hodpars_swigregister(hodpars)

def dxi_gg(arg1, arg2):
    r"""dxi_gg(double arg1, void * arg2) -> double"""
    return _hod.dxi_gg(arg1, arg2)

def dxi_gd(arg1, arg2):
    r"""dxi_gd(double arg1, void * arg2) -> double"""
    return _hod.dxi_gd(arg1, arg2)

def dwp(arg1, arg2):
    r"""dwp(double arg1, void * arg2) -> double"""
    return _hod.dwp(arg1, arg2)

def dwp2(arg1, arg2):
    r"""dwp2(double arg1, void * arg2) -> double"""
    return _hod.dwp2(arg1, arg2)

def dsigma(arg1, arg2):
    r"""dsigma(double arg1, void * arg2) -> double"""
    return _hod.dsigma(arg1, arg2)

def dwp_kaiser(x, params):
    r"""dwp_kaiser(double x, void * params) -> double"""
    return _hod.dwp_kaiser(x, params)

def dxiggbarbar(x, params):
    r"""dxiggbarbar(double x, void * params) -> double"""
    return _hod.dxiggbarbar(x, params)

def dxiggbar(x, params):
    r"""dxiggbar(double x, void * params) -> double"""
    return _hod.dxiggbar(x, params)

def auxncen(x, params):
    r"""auxncen(double x, void * params) -> double"""
    return _hod.auxncen(x, params)
class hod(cosmology):
    r"""Proxy of C++ hod class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(hod self, cosmo arg2, hodpars arg3) -> hod
        __init__(hod self) -> hod
        Initializes hod and cosmology object

        :Parameters:

        -  cosmo structure:
            Om0 : Matter density parameter
            Omk : Curvature parameter
            w0 : Dark energy equation of state parameter
            wa : Dark energy equation of state parameter
            Omb : Baryon density parameter
            h : Hubble parameter
            th : CMB temperature
            s8 : sigma8
            nspec : power spectrum index
            ximax : Parameter psi defined in van den Bosch 2013, only relevant for halo model calculation
            cfac : Constant multiplicative factor for the c-M relation
        -  hodp structure:
            Mmin : Minimum halo mass in the central HOD
            siglogM : Scatter in halo masses in the central HOD
            Msat : Satellite halo occupation mass scale
            alpsat : Slope of the satellite halo occupation
            Mcut : Cut off mass scale of the satellite halo occupation
            fac : Unused parameter
            csbycdm : Multiplicative factor for satellite concentrations


        :Returns:

        -   HOD object

        Without any inputs, initializes to flat WMAP3 LCDM cosmology, cfac=1.0, ximax=log10(8.0).

        :Examples:

        >>> import hod as h
        >>> p = h.cosmo()
        >>> q = h.hodpars()
        >>> p.Om0 = 0.307115
        >>> p.w0 = -1
        >>> p.wa = 0
        >>> p.Omk = 0.0
        >>> p.hval = 0.6777
        >>> p.Omb = 0.048206
        >>> p.th = 2.726
        >>> p.s8 = 0.8228
        >>> p.nspec = 0.96
        >>> p.ximax = log10(8.0)
        >>> p.cfac = 1.0
        >>> q.Mmin = 13.0
        >>> q.siglogM = 0.5
        >>> q.Msat = 14.0
        >>> q.alpsat = 1.0
        >>> q.Mcut = 13.5
        >>> q.csbycdm = 1.0
        >>> q.fac = 1.0
        >>> a = h.hod(p, q)
        >>> help(a)


        """
        _hod.hod_swiginit(self, _hod.new_hod(*args))

    def ncen(self, logM):
        r"""
        ncen(hod self, double logM) -> double
        Average number of central galaxies in halo of mass M

        :Parameters:

        -   log M200: logarithm of the mass of the halo

        :Returns:

        -   Average number of central galaxies in the halo


        :Examples:

        >>> import hod as h
        >>> a = h.hod()
        >>> a.ncen(12.0)


        """
        return _hod.hod_ncen(self, logM)

    def nsat(self, logM):
        r"""
        nsat(hod self, double logM) -> double
        Average number of satellite galaxies in halo of mass M

        :Parameters:

        -   log M200: logarithm of the mass of the halo

        :Returns:

        -   Average number of satellite galaxies in the halo


        :Examples:

        >>> import hod as h
        >>> a = h.hod()
        >>> a.nsat(12.0)


        """
        return _hod.hod_nsat(self, logM)

    def ncenz(self, z):
        r"""
        ncenz(hod self, double z) -> double
        Average number density of central galaxies at redshift z

        :Parameters:

        -   z: Redshift

        :Returns:

        -   Average number density of central galaxies at redshift z


        :Examples:

        >>> import hod as h
        >>> a = h.hod()
        >>> a.ncenz(0.5)


        """
        return _hod.hod_ncenz(self, z)

    def nsatz(self, z):
        r"""
        nsatz(hod self, double z) -> double
        Average number density of satellite galaxies at redshift z

        :Parameters:

        -   z: Redshift

        :Returns:

        -   Average number density of satellite galaxies at redshift z


        :Examples:

        >>> import hod as h
        >>> a = h.hod()
        >>> a.nsatz(0.5)


        """
        return _hod.hod_nsatz(self, z)

    def avmass_tot(self, z):
        r"""
        avmass_tot(hod self, double z) -> double
        Average halo mass of all galaxies

        :Parameters:

        -   z: Redshift

        :Returns:

        -   Average halo mass of all galaxies at redshift z, normalized by 1e12 hinv
            Msun


        :Examples:

        >>> import hod as h
        >>> a = h.hod()
        >>> a.avmass_tot(0.5)


        """
        return _hod.hod_avmass_tot(self, z)

    def avmass_cen(self, z):
        r"""
        avmass_cen(hod self, double z) -> double
        Average halo mass of central galaxies

        :Parameters:

        -   z: Redshift

        :Returns:

        -   Average halo mass of central galaxies at redshift z, normalized by 1e12 hinv
            Msun


        :Examples:

        >>> import hod as h
        >>> a = h.hod()
        >>> a.avmass_cen(0.5)


        """
        return _hod.hod_avmass_cen(self, z)

    def galaxy_bias(self, z):
        r"""
        galaxy_bias(hod self, double z) -> double
        Average halo bias of all galaxies at redshift z

        :Parameters:

        -   z: Redshift

        :Returns:

        -   Average halo bias of all galaxies at redshift z


        :Examples:

        >>> import hod as h
        >>> a = h.hod()
        >>> a.galaxy_bias(0.5)


        """
        return _hod.hod_galaxy_bias(self, z)

    def gets8(self):
        r"""
        gets8(hod self) -> double
        Output value of sigma8

        :Parameters:

        -   None : No inputs

        :Returns:

        -   sigma8 : sigma8

        :Examples:

        >>> a.gets8()

        """
        return _hod.hod_gets8(self)

    def geth(self):
        r"""
        geth(hod self) -> double
        Output value of h value

        :Parameters:

        -   None : No input parameters

        :Returns:

        -   h : Hubble parameter

        :Examples:

        >>> a.geth()

        """
        return _hod.hod_geth(self)

    def getOmb(self):
        r"""
        getOmb(hod self) -> double
        Output value of Omegab

        :Parameters:

        -   None : No input parameters

        :Returns:

        -   Omegab : Baryon density parameter

        :Examples:

        >>> a.getOmb()

        """
        return _hod.hod_getOmb(self)

    def getOmk(self):
        r"""
        getOmk(hod self) -> double
        Output value of curvature parameter

        :Parameters:

        -   None : No input parameters

        :Returns:

        -   Omk : Curvature parameter

        :Examples:

        >>> a.getOmk()

        """
        return _hod.hod_getOmk(self)

    def set_cfactor(self, cfac):
        r"""
        set_cfactor(hod self, double cfac) -> double
        Set multiplicative constant to multiply all dark matter concentrations

        :Parameters:

        -   cfac : multiplicative constant

        :Returns:

        -   None : No return value

        :Examples:

        >>> a.set_cfactor(1.0)

        """
        return _hod.hod_set_cfactor(self, cfac)

    def D2gg_num(self, k, z):
        r"""
        D2gg_num(hod self, double k, double z) -> double
        Power per logarithmic k interval in the galaxy galaxy power spectrum Delta^2(k,z)

        :Parameters:

        -   k: Wavenumber (in h Mpc^{-1})
        -   z: Redshift

        :Returns:

        -   Delta_gg^2(k,z)

        :Examples:

        >>> a.D2gg_num(0.1,0.0)


        """
        return _hod.hod_D2gg_num(self, k, z)

    def D2gd_num(self, k, z):
        r"""
        D2gd_num(hod self, double k, double z) -> double
        Power per logarithmic k interval in the galaxy matter power spectrum Delta^2(k,z)

        :Parameters:

        -   k: Wavenumber (in h Mpc^{-1})
        -   z: Redshift

        :Returns:

        -   Delta_gd^2(k,z)

        :Examples:

        >>> a.D2gd_num(0.1,0.0)


        """
        return _hod.hod_D2gd_num(self, k, z)

    def xigg_num(self, r, z):
        r"""
        xigg_num(hod self, double r, double z) -> double
        Galaxy-galaxy correlation function at distance radius and redshift z

        :Parameters:

        -   r: Wavenumber (in h Mpc^{-1})
        -   z: Redshift

        :Returns:

        -   xi_gg(r,z)

        :Examples:

        >>> a.xigg_num(0.1,0.0)


        """
        return _hod.hod_xigg_num(self, r, z)

    def xigd_num(self, r, z):
        r"""
        xigd_num(hod self, double r, double z) -> double
        Galaxy-matter correlation function at distance radius and redshift z

        :Parameters:

        -   r: Wavenumber (in h Mpc^{-1})
        -   z: Redshift

        :Returns:

        -   xi_gd(r,z)

        :Examples:

        >>> a.xigd_num(0.1,0.0)


        """
        return _hod.hod_xigd_num(self, r, z)

    def Wp_ESD(self, z, wpbins, esdbins, rp, esdrp, wp, esd, esdbins2, pimax, reset=True):
        r"""
        Wp_ESD(hod self, double z, int wpbins, int esdbins, double [] rp, double [] esdrp, double [] wp, double [] esd, int esdbins2, double pimax, bool reset=True) -> double
        Return projected galaxy correlation and ESD 

        :Parameters:

        -   z: Redshift
        -   wpbins: Number of radial bins for the projected correlation function (wp)
        -   esdbins: Number of radial bins for the excess surface density (ESD)
        -   rp: A c-array of projected radii for wp (see below for c-array)
        -   esdrp: A c-array of projected radii for ESD
        -   wp: A c-array to store results for wp
        -   esd: A c-array to store results for ESD
        -   esdbins2: Number of radial bins for the surface density calculation
            (>esdbins+4 typically)
        -   pimax: The line of sight integration length
        -   reset: (optional) reset halo exclusion related calculations, default=1

        :Returns:

        -   status: 0 on success, wp results are stored in wp array, and esd in ESD
            array

        :Examples:

        >>> a.Wp_ESD(0.1, 12, 12, rp, esdrp, wp, esd, 16, 100.0)

        To get a c-array from a numpy array. Use the following python function:

        :Examples:

        >>> def getdblarr(r):
        >>>     temp=h.doubleArray(r.size)
        >>>     for i in range(r.size):
        >>>         temp[i]=r[i]
        >>>     return temp


        Get a numpy-array from a c-array. Use the following python function:

        :Examples:

        >>> def getnparr(r,n):
        >>>     temp=np.zeros(n)
        >>>     for i in range(n):
        >>>         temp[i]=r[i]
        >>>     return temp

        """
        return _hod.hod_Wp_ESD(self, z, wpbins, esdbins, rp, esdrp, wp, esd, esdbins2, pimax, reset)

    def Wp(self, z, wpbins, rp, wp, pimax, reset=True):
        r"""
        Wp(hod self, double z, int wpbins, double [] rp, double [] wp, double pimax, bool reset=True) -> double
        Return projected galaxy correlation

        :Parameters:

        -   z: Redshift
        -   wpbins: Number of radial bins for the projected correlation function (wp)
        -   rp: A c-array of projected radii for wp (see hod::Wp_ESD for c-array)
        -   wp: A c-array to store results for wp
        -   pimax: The line of sight integration length
        -   reset: (optional) reset halo exclusion related calculations, default=1

        :Returns:

        -   status: 0 on success, wp results are stored in wp array

        :Examples:

        >>> a.Wp(0.1, 12, rp, wp, 100.0)


        """
        return _hod.hod_Wp(self, z, wpbins, rp, wp, pimax, reset)

    def Wp_Kaiser(self, z, wpbins, rp, wp, pimax, reset=True):
        r"""
        Wp_Kaiser(hod self, double z, int wpbins, double [] rp, double [] wp, double pimax, bool reset=True) -> double
        Return projected galaxy correlation accounting for the effects of redshift
        space distortions

        :Parameters:

        -   z: Redshift
        -   wpbins: Number of radial bins for the projected correlation function (wp)
        -   rp: A c-array of projected radii for wp (see hod::Wp_ESD for c-array)
        -   wp: A c-array to store results for wp
        -   pimax: The line of sight integration length
        -   reset: (optional) reset halo exclusion related calculations, default=1

        :Returns:

        -   status: 0 on success, wp results are stored in wp array

        :Examples:

        >>> a.Wp_Kaiser(0.1, 12, rp, wp, 100.0)


        """
        return _hod.hod_Wp_Kaiser(self, z, wpbins, rp, wp, pimax, reset)

    def ESD(self, z, esdbins, rp, esd, esdbins2, reset=True):
        r"""
        ESD(hod self, double z, int esdbins, double [] rp, double [] esd, int esdbins2, bool reset=True) -> double
        Return the weak lensing signal

        :Parameters:

        -   z: Redshift
        -   esdbins: Number of radial bins for the excess surface density (ESD)
        -   esdrp: A c-array of projected radii for ESD (see hod::Wp_ESD for c-array)
        -   esd: A c-array to store results for ESD
        -   esdbins2: Number of radial bins for the surface density calculation
            (>esdbins+4 typically)
        -   reset: (optional) reset halo exclusion related calculations, default=1

        :Returns:

        -   status: 0 on success, wp results are stored in wp array, and esd in ESD
            array

        :Examples:

        >>> a.ESD(0.1, 12, esdrp, esd, 16)


        """
        return _hod.hod_ESD(self, z, esdbins, rp, esd, esdbins2, reset)

    def Sigma(self, z, esdbins, rp, sigma, reset=True, xfgm_m0=-99.0, xfgm_slp=-99.0, pimax=-80.0):
        r"""Sigma(hod self, double z, int esdbins, double [] rp, double [] sigma, bool reset=True, double xfgm_m0=-99.0, double xfgm_slp=-99.0, double pimax=-80.0) -> double"""
        return _hod.hod_Sigma(self, z, esdbins, rp, sigma, reset, xfgm_m0, xfgm_slp, pimax)

    def pspec_halomodel(self, z):
        r"""pspec_halomodel(hod self, double z) -> double"""
        return _hod.hod_pspec_halomodel(self, z)

    def scale_dep_bias_crossr(self, arg2, arg3, arg4, arg5, arg6, arg7):
        r"""
        scale_dep_bias_crossr(hod self, double arg2, int arg3, double [] arg4, double [] arg5, double [] arg6, bool arg7) -> double
        Return the scale dependent bias and the cross-correlation coefficient

        :Parameters:

        -   z: Redshift
        -   rbins: Number of radial bins 
        -   rp: A c-array of 3-d radii (see hod::Wp_ESD for c-array)
        -   bias: A c-array to store results for scale dependent bias
        -   crossr: A c-array to store results for cross-correlation coefficient
        -   reset: (optional) reset halo exclusion related calculations, default=1

        :Returns:

        -   status: 0 on success, bias and cross-correlation results stored in array

        :Examples:

        >>> a.scale_dep_bias_crossr(0.1, 12, rr, bias, crossr)


        """
        return _hod.hod_scale_dep_bias_crossr(self, arg2, arg3, arg4, arg5, arg6, arg7)

    def resetz(self, arg2):
        r"""
        resetz(hod self, double arg2)
        Reset a number of splines initialized to perform gg, and gd power spectrum
        calculations

        :Parameters:

        -   z: Redshift

        :Returns:

        -   None: No return value

        :Examples:

        >>> a.resetz(0.3)


        """
        return _hod.hod_resetz(self, arg2)

    def hod_free(self):
        r"""hod_free(hod self)"""
        return _hod.hod_hod_free(self)

    def _print(self, *args):
        r"""
        _print(hod self, cosmo arg2, hodpars arg3)
        _print(hod self, FILE *& arg2, cosmo arg3, hodpars arg4, double arg5, double arg6)
        _print(hod self, FILE *& arg2, cosmo arg3, hodpars arg4)
        _print(hod self)
        """
        return _hod.hod__print(self, *args)

    def sethalo_exc(self, arg2):
        r"""
        sethalo_exc(hod self, bool arg2)
        Set halo exclusion module

        :Parameters:

        -   haloexc: Enable halo exclusion or not

        :Returns:

        -   None: No return value

        :Examples:

        >>> a.sethalo_exc(True)


        """
        return _hod.hod_sethalo_exc(self, arg2)

    def set_cen_offset_params(self, fcen_off, off_rbyrs):
        r"""
        set_cen_offset_params(hod self, double fcen_off, double off_rbyrs)
        Set off centering parameters

        :Parameters:

        -   fcen_off: Fraction of off-centered halos
        -   off_rbyrs: offcentering kernel in units of scale radius of all halos

        :Returns:

        -   None: No return value

        :Examples:

        >>> a.set_cen_offset_params(0.4, 1.0)


        """
        return _hod.hod_set_cen_offset_params(self, fcen_off, off_rbyrs)

    def set_inc_params(self, inc_alp, inc_xM):
        r"""
        set_inc_params(hod self, double inc_alp, double inc_xM)
        Set incompleteness parameters

        :Parameters:

        -   inc_alp: Slope for the incompleteness
        -   inc_xM: Logarithm of mass above which sample is complete, below a log-linear form with slope inc_alp

        :Returns:

        -   None: No return value

        :Examples:

        >>> a.set_inc_params(1.0, 12.0)


        """
        return _hod.hod_set_inc_params(self, inc_alp, inc_xM)

    def hod_renew(self, *args):
        r"""
        hod_renew(hod self, cosmo p, hodpars h)
        hod_renew(hod self, hodpars h)
        """
        return _hod.hod_hod_renew(self, *args)
    whichopt = property(_hod.hod_whichopt_get, _hod.hod_whichopt_set, doc=r"""whichopt : int""")

    def set_whichopt(self, whichopt):
        r"""set_whichopt(hod self, int whichopt)"""
        return _hod.hod_set_whichopt(self, whichopt)
    __swig_destroy__ = _hod.delete_hod

# Register hod in _hod:
_hod.hod_swigregister(hod)

